Algoritmo "ORDEM_INVERSA"
var
   nome: vetor[1..10] de caracter
   i: inteiro
inicio
   para i de 1 ate 10 faca
      escreva("Digite um nome: ")
      leia(nome[i])
   fimpara
   
   escreval("")
   escreval(nome[10])
   escreval(nome[9])
   escreval(nome[8])
   escreval(nome[7])
   escreval(nome[6])
   escreval(nome[5])
   escreval(nome[4])
   escreval(nome[3])
   escreval(nome[2])
   escreval(nome[1])
Fimalgoritmo